# Generated by Django 5.2.3 on 2025-07-07 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('stocks', 'Hisa za Kampuni'), ('bonds', 'Dhamana'), ('real_estate', 'Mali Isiyohamishika'), ('money_market', 'Soko la Fedha'), ('mutual_funds', 'Mfuko wa Uongozi'), ('fixed_deposit', 'Amana ya Muda'), ('business', 'Biashara'), ('agriculture', 'Kilimo'), ('digital_assets', 'Mali za Kidijitali')], max_length=50)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_return', models.DecimalField(decimal_places=2, help_text='Expected annual return in percentage', max_digits=5)),
                ('risk_level', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=20)),
                ('description', models.TextField()),
                ('local_description', models.TextField(help_text='Description in Swahili')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=20)),
                ('investment_timeline', models.IntegerField(help_text='Investment timeline in months')),
                ('finacial_goals', models.TextField(help_text='Describe your financial goals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommmended_amount', models.DecimalField(decimal_places=2, help_text='Recommended investment amount', max_digits=10)),
                ('ai_rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.investment')),
                ('risk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.riskprofile')),
            ],
        ),
    ]
