# Generated by Django 5.2.3 on 2025-07-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_rename_finacial_goals_riskprofile_financial_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
