# Generated by Django 5.2.3 on 2025-07-10 19:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investment_updated_at_riskprofile_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['name'], 'verbose_name': 'Investment', 'verbose_name_plural': 'Investments'},
        ),
        migrations.AlterModelOptions(
            name='investmentrecommendation',
            options={'ordering': ['-confidence_score', '-recommended_amount'], 'verbose_name': 'Investment Recommendation', 'verbose_name_plural': 'Investment Recommendations'},
        ),
        migrations.AlterModelOptions(
            name='riskprofile',
            options={'verbose_name': 'Risk Profile', 'verbose_name_plural': 'Risk Profiles'},
        ),
        migrations.AlterUniqueTogether(
            name='investmentrecommendation',
            unique_together={('risk_profile', 'investment')},
        ),
        migrations.AddField(
            model_name='investment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this investment is currently available'),
        ),
        migrations.AddField(
            model_name='investmentrecommendation',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score (0-1)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='investmentrecommendation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investmentrecommendation',
            name='recommended_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Recommended investment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='investmentrecommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='expected_return',
            field=models.DecimalField(decimal_places=2, help_text='Expected annual return in percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='investment',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='investmentrecommendation',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='investments.investment'),
        ),
        migrations.AlterField(
            model_name='investmentrecommendation',
            name='risk_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='investments.riskprofile'),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='investment_timeline',
            field=models.IntegerField(help_text='Investment timeline in months', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RemoveField(
            model_name='investmentrecommendation',
            name='recommmended_amount',
        ),
    ]
