# Generated by Django 5.2.3 on 2025-07-10 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_alter_investmentrecommendation_confidence_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentrecommendation',
            name='confidence_score',
            field=models.DecimalField(decimal_places=2, help_text='AI confidence score (0-1)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
